### ISSUE TITLE
app/cogs/mst_line.py 136行目~のテキストメッセージ作成部分のリファクタリング

### ISSUE THREAD

**Issue by sekine-1113** [maguro-alternative/discordfast#68]
## 目的

ソースコードの可読性を高める。

## 現状

if文が連なっていて、今後他のメッセージを追加するときに追加し忘れる可能性がある。

https://github.com/maguro-alternative/discordfast/blob/639e285dabd6b55f4fc4645fe124b7bfdeb1cda7/app/cogs/mst_line.py#L135-L151

## 修正案

pythonではdict型のキーにオブジェクト等も使用できる。そのため、dictで管理すれば以下のように簡潔に記述することができる。

```python
messageTexts = {
    discord.MessageType.new_member: f"{user_name}が参加しました。",
    discord.MessageType.premium_guild_subscription: f"{user_name}がサーバーブーストしました。",
    discord.MessageType.premium_guild_tier_1: f"{user_name}がサーバーブーストし、レベル1になりました！！！！！！！！",
    discord.MessageType.premium_guild_tier_2: f"{user_name}がサーバーブーストし、レベル2になりました！！！！！！！！！",
    discord.MessageType.premium_guild_tier_3: f"{user_name}がサーバーブーストし、レベル3になりました！！！！！！！！！！！"
}
messagetext = messageTexts.get(message.type, f"{message.channel.name}にて、{user_name}")
```

**Comment by maguro-alternative** [comment]
解釈としては
- メッセージタイプをキーにして、それに該当するメッセージをそれぞれ格納。
- 該当するメッセージだった場合に送るメッセージをgetで取得。
- 該当するものではない場合(通常のメッセージ)、メッセージ内容を格納。

ということですね。

getの第二引数にdefaultつければ解釈できそうです。
ありがとうございます😊
